In [1]:
import numpy as np

# 1. 定义 Steane [7,1,3] 码的奇偶校验矩阵
# 这是一个 3行 x 7列 的矩阵。
# Hx 用来检测 Z 错误，Hz 用来检测 X 错误。
H = np.array([
    [0, 0, 0, 1, 1, 1, 1],
    [0, 1, 1, 0, 0, 1, 1],
    [1, 0, 1, 0, 1, 0, 1]
])

Hx = H
Hz = H

print("=== 1. 验证量子 CSS 正交性约束 ===")
# 数学约束: Hx * Hz.T 模2等于 0
# numpy 中的 dot 是矩阵乘法， % 2 是模2运算
orthogonality_check = np.dot(Hx, Hz.T) % 2
print("Hx * Hz^T (mod 2) =\n", orthogonality_check)
if np.all(orthogonality_check == 0):
    print("✅ 正交性验证通过！这是一个合法的量子校验矩阵组合。\n")
else:
    print("❌ 验证失败，这不是合法的量子码。\n")


print("=== 2. 模拟错误与计算综合征 (Syndrome) ===")
# 假设我们有7个物理量子比特，初始状态没有错误
# 现在，假设第 4 个比特（索引为3）发生了“比特翻转（X错误）”
e_X = np.array([0, 0, 0, 1, 0, 0, 0])
print("发生的 X 错误模式 (e_X):", e_X)

# 为了检测 X 错误，我们需要用 Hz 矩阵去乘以错误向量
# 综合征 s_z = Hz * e_X (mod 2)
s_Z = np.dot(Hz, e_X) % 2
print("测量得到的综合征 (s_Z):", s_Z)

# 分析：看 Hz 矩阵，s_Z 的结果 [1, 0, 0] 恰好等于 Hz 矩阵的第 4 列 (索引3)！
# 这意味着经典解码器（或者BP算法）看到 [1, 0, 0] 这个报错信号时，
# 就能反推出：“哦，是第 4 个比特发生了X错误！”


print("\n=== 3. 模拟更复杂的混合错误 ===")
# 假设第 2 个比特发生了 X 错误，第 6 个比特发生了 Z 错误
e_X_mix = np.array([0, 1, 0, 0, 0, 0, 0])
e_Z_mix = np.array([0, 0, 0, 0, 0, 1, 0])
print("混合 X 错误模式 (e_X):", e_X_mix)
print("混合 Z 错误模式 (e_Z):", e_Z_mix)

# 独立检测
s_Z_mix = np.dot(Hz, e_X_mix) % 2
s_X_mix = np.dot(Hx, e_Z_mix) % 2

print("测得的 Z 综合征 (对应X错误):", s_Z_mix) # 结果应为 [0, 1, 0]
print("测得的 X 综合征 (对应Z错误):", s_X_mix) # 结果应为 [1, 1, 0]
# 解码器看到 s_Z_mix=[0,1,0]，对应 Hz 第 2 列，判定第2个比特发生 X 错误
# 解码器看到 s_X_mix=[1,1,0]，对应 Hx 第 6 列，判定第6个比特发生 Z 错误

=== 1. 验证量子 CSS 正交性约束 ===
Hx * Hz^T (mod 2) =
 [[0 0 0]
 [0 0 0]
 [0 0 0]]
✅ 正交性验证通过！这是一个合法的量子校验矩阵组合。

=== 2. 模拟错误与计算综合征 (Syndrome) ===
发生的 X 错误模式 (e_X): [0 0 0 1 0 0 0]
测量得到的综合征 (s_Z): [1 0 0]

=== 3. 模拟更复杂的混合错误 ===
混合 X 错误模式 (e_X): [0 1 0 0 0 0 0]
混合 Z 错误模式 (e_Z): [0 0 0 0 0 1 0]
测得的 Z 综合征 (对应X错误): [0 1 0]
测得的 X 综合征 (对应Z错误): [1 1 0]
